include file("application.conf")

ktor {
    environment = local
}

configuration {
    useAuthentication = false
}

osConfiguration {
    endpointUrl = "https://155.55.1.82:9080/ostilbakekrevingapi"
}