ktor {
    environment = local
}

configuration {
    naisAppName = ""
    profile = ""
    useAuthentication = ""
}

azureAdProperties {
    clientId = ""
    wellKnownUrl = ""
}

osConfiguration {
    endpointUrl = ""
    trustStore = ""
    trustStorePassword = ""
}