include file("defaults.properties")

ktor {
    environment = local
}

configuration {
    naisAppName = "sokos-os-ekstern-api"
    useAuthentication = true
}

azureAdProperties {
    clientId = ${AZURE_APP_CLIENT_ID}
    wellKnownUrl = ${AZURE_APP_WELL_KNOWN_URL}
}

osConfiguration {
    endpointUrl = ""
    trustStore = ${NAV_TRUSTSTORE_PATH}
    trustStorePassword = ${NAV_TRUSTSTORE_PASSWORD}
}