apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-os-ekstern-api
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-os-ekstern-api.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - ipv4: 155.55.1.82  # OS via zos-connect
          ports:
            - port: 9080

  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # ZOS-Connect
    - name: OS_ENDPOINT_URL
      value: "https://155.55.1.82:9080"