apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-ktor-template
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-ktor-template.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
    outbound:
      rules:
        - application: logging
          namespace: nais-system

  env:
    - name: USE_AUTHENTICATION
      value: "true"